---
- hosts: etcd-a
  become: yes
  remote_user: dev
  vars:
    etcd_peers_group: etcd
    etcd_version: v2.2.5
    etcd_interface: eth0
    cluster_domain: '{{cbt_cloud.domain}}'
    etcd_peers_group: etcd-a
    etcd_listen_peer_urls:  '{{ etcd_peer_url_scheme}}://0.0.0.0:{{etcd_peer_port}}'
    etcd_listen_client_urls: "{{ etcd_client_url_scheme }}://0.0.0.0:{{ etcd_client_port }}"
  roles:
    - ansible-etcd

# - hosts: flannel-bootstrap
#   become: yes
#   remote_user: dev
#   vars:
#     - etcd_prefix: /coreos.com/network/config
#     - network_config: |
#         {
#             "Network": "10.2.0.0/16",
#             "SubnetMin": "10.2.100.0",
#             "SubnetMax": "10.2.199.0",
#             "Backend": {
#                 "Type": "vxlan",
#                 "VNI": 2405
#             }
#         }
#
#   tasks:
#     - name: push flannel network config to etcd
#       shell: etcdctl set {{etcd_prefix}} '{{network_config}}'
