---
- shell: test -f /usr/local/sbin/{{ item }}
  register: test_result
  with_items:
    - etcd
    - etcdctl
- name: ensure etcd and etcdctl were copied
  assert:
    that:
      - "{{ item.rc }} == 0"
  with_items: test_result.results
- shell: curl -qs "http://{{ hostvars[inventory_hostname]['ansible_eth1']['ipv4']['address'] }}:2379/v2/machines" | grep -o 2379 | wc -l
  register: curl_result
- name: ensure cluster was created
  assert:
    that:
      - 'curl_result.stdout == "3"'
