---
galaxy_info:
  author: John Dewey
  description: Install and manage etcd.
  company:
  license: MIT
  min_ansible_version: 1.2
  platforms:
  - name: Ubuntu
    versions:
    - all
    - quantal
    - raring
    - saucy
    - trusty
  categories:
  - system
dependencies: []
